from sqlalchemy.orm import Session
from database import SessionLocal
import model

# 1. Create a new Session (The "Bank Teller")
db = SessionLocal()

try:
    # 2. Create a new User object (The "Data")
    new_user = model.User(
        id = 1,
        email="utkarsh@example.com", 
        hashed_password="secret_password_123",
        is_active = True,
        username = "Hello123"
    )

    # 3. Add it to the "Staging Area"
    db.add(new_user)

    # 4. COMMIT: This is the "Save" button that pushes it to Postgres
    db.commit()

    # 5. Refresh to get the ID generated by the database
    db.refresh(new_user)
    print(f"✅ Success! Created user with ID: {new_user.id}")

except Exception as e:
    print(f"❌ Error: {e}")
    db.rollback() # Undo if something goes wrong
finally:
    db.close() # Always close the connection